import type { Metadata } from "next";
import Navbar from "./components/navbar";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full bg-white" lang="en">
      <body className="h-full">
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
